color0 #45483c
color1 #ffb4ab
color2 #b8cf84
color3 #c2caaa
color4 #a0d0c8
color5 #b8cf84
color6 #c2caaa
color7 #e3e3d7
color8 #909284
color9 #ffb4ab
color10 #b8cf84
color11 #c2caaa
color12 #a0d0c8
color13 #b8cf84
color14 #c2caaa
color15 #e3e3d7

cursor                #e3e3d7
cursor_text_color     #12140d
background            #12140d
foreground            #e3e3d7
selection_foreground  #c6c8b9
selection_background  #45483c
active_border_color   #b8cf84
inactive_border_color #45483c
url_color             #b8cf84

active_tab_foreground   #263500
active_tab_background   #b8cf84
inactive_tab_foreground #c6c8b9
inactive_tab_background #45483c
cursor_trail_color      #c6c8b9
