color0 #302a22
color1 #fd4663
color2 #c1aa8b
color3 #aeb181
color4 #85ad9c
color5 #d3c2ac
color6 #ced0af
color7 #f3f2f2
color8 #71695c
color9 #fd4663
color10 #c1aa8b
color11 #aeb181
color12 #85ad9c
color13 #d3c2ac
color14 #ced0af
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #231f1a
background            #231f1a
foreground            #f3f2f2
selection_foreground  #b6b3af
selection_background  #302a22
active_border_color   #c1aa8b
inactive_border_color #302a22
url_color             #c1aa8b

active_tab_foreground   #221f1b
active_tab_background   #c1aa8b
inactive_tab_foreground #b6b3af
inactive_tab_background #302a22
cursor_trail_color      #b6b3af
