# Noctalia theme for snappy-switcher

[colors]
background = #12140daa
card_bg = #1e2019aa
card_selected =  #34362eff
text_color = #d4ec9ddd
subtext_color =  #d4ec9dcc
border_color =  #909284ff
bundle_bg = #424a31ff
badge_bg =  #c2caaaaa
badge_text_color = #2c331daa
badge_bg_selected = #c2caaacc
badge_text_color_selected = #2c331dff