# Noctalia theme for snappy-switcher

[colors]
background = #17130baa
card_bg = #241f17aa
card_selected =  #3a342bff
text_color = #ffdea8dd
subtext_color =  #ffdea8cc
border_color =  #9a8f80ff
bundle_bg = #54442aff
badge_bg =  #dac3a0aa
badge_text_color = #3c2e15aa
badge_bg_selected = #dac3a0cc
badge_text_color_selected = #3c2e15ff