-- Generated by HyprMod

-- Settings
hl.config({
    cursor = {
        enable_hyprcursor = false,
    },
    ecosystem = {
        enforce_permissions = true,
        no_donation_nag = true,
        no_update_news = true,
    },
    misc = {
        disable_splash_rendering = true,
        vrr = 1,
    },
    xwayland = {
        force_zero_scaling = true,
    },
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "1920x1200@60.00Hz",
    position = "0x0",
    scale = 1.25,
    cm = "srgb",
    sdrbrightness = 0.5,
    sdr_min_luminance = 0,
    sdr_max_luminance = 617,
    min_luminance = 0,
    max_luminance = 617,
    max_avg_luminance = 400,
})
