color0 #212530
color1 #fd4663
color2 #8b98c1
color3 #8d81b1
color4 #a484ae
color5 #acb5d3
color6 #b7afd0
color7 #f2f2f3
color8 #636772
color9 #fd4663
color10 #8b98c1
color11 #8d81b1
color12 #a484ae
color13 #acb5d3
color14 #b7afd0
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #000000
background            #000000
foreground            #f2f2f3
selection_foreground  #afb1b6
selection_background  #212530
active_border_color   #8b98c1
inactive_border_color #0b0f19
url_color             #8b98c1

active_tab_foreground   #1b1d22
active_tab_background   #8b98c1
inactive_tab_foreground #afb1b6
inactive_tab_background #0b0f19
cursor_trail_color      #afb1b6
