color0 #46464e
color1 #ffb4ab
color2 #bdc4f2
color3 #c4c5d9
color4 #e9b8dc
color5 #bdc4f2
color6 #c4c5d9
color7 #e4e1e5
color8 #909099
color9 #ffb4ab
color10 #bdc4f2
color11 #c4c5d9
color12 #e9b8dc
color13 #bdc4f2
color14 #c4c5d9
color15 #e4e1e5

cursor                #e4e1e5
cursor_text_color     #131316
background            #131316
foreground            #e4e1e5
selection_foreground  #c7c5cf
selection_background  #46464e
active_border_color   #bdc4f2
inactive_border_color #46464e
url_color             #bdc4f2

active_tab_foreground   #272e53
active_tab_background   #bdc4f2
inactive_tab_foreground #c7c5cf
inactive_tab_background #46464e
cursor_trail_color      #c7c5cf
